spring.application.name=demo
management.endpoints.web.exposure.include=*

spring.config.import=optional:classpath:.env

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false   

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Cache
spring.cache.redis.time-to-live=3600s

# Custom configs
cache.ttl.ms=3600s
rate-limiter.max-requests=5
rate-limiter.time-window=60