spring.application.name=demo
management.endpoints.web.exposure.include=*

spring.config.import=optional:classpath:.env

spring.datasource.url=jdbc:mysql://testdb-krishnaakhil-58aa.f.aivencloud.com:22596/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=${AIVEN_PASSWORD}AVNS_wNB7SGdzh2B7x4WDR1N
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=2170        
spring.cache.redis.time-to-live=3600s

cache.ttl.ms=3600s
rate-limiter.max-requests=5
rate-limiter.time-window=60  